language: go
go:
  - 1.5

env:
  global:
    - PATH="$GOPATH/bin:$PATH"
    - RELEASES_PATH=/tmp/releases

script:
  - go test -v

before_deploy:
  - go get github.com/laher/goxc
  - goxc -tasks 'xc archive' -bc 'windows darwin linux' -d "$RELEASES_PATH" -resources-include 'README*'

deploy:
  provider: releases
  api_key:
    secure: UJqNdKtpFFyQLPmCA/agu9kOqKYwC86CoEZvQD/C9yK4Rj88U5LxfAXI+2gWnFEXVOFFYIBWMNFB7e0lI+R3cY6zplJi3P6iO7XMSwbhL/MEiQAhCf1XfDM9tQTSo35tKZkqeiZ6uu0CKdH2cMuVgC/nN2Hv7xaR2jG30c9kI1Wmnmt1JH7QrbdggCtEQw+f6X5Nyrr92kSxmXXju/QFjiNeo03jaEtiich9tq1zttYS813q2FxYS+my1/W92+fYc9RpuLM5ZbTWdxJ/1B+fWl9EjYka1qxz2r8SMG0K3FWTzGIEOSnVeOvzeYjrshq+1VFUCXXHzWWSw8vv9LkPP+kNjK1wHZS3FhKE7fF4+VyuqbmRU05UXGIvoyTOyYyClnXk0KLUEsd5oNjSwNbnTB4mQCZqxtTBdN673ipgkgBdXepDczTZT6CmWexMQYBqsmPUh8lTcvA2k0xuAAMfe+4UW8hbyvyy5P3CDfP4uk4cILgcwhUJ363JbPF27xUwspEc5JDXFL5zgK9dm0ZBHQBroQseaWWyrs1jOKSRm0SUd530enfyp/IofVtaMWkBpvKOMfsnhvij1S42AABWqTAG0MceK6/Uk/xBpGznK6rQPJljnoqId9RpUnoWN9RHph+WBV5I4WMgj8KrW8UQoVqR+G9LeEUep6HF1JRmotQ=
  file:
    - $RELEASES_PATH/snapshot/circlecrossgame_windows_386.zip
    - $RELEASES_PATH/snapshot/circlecrossgame_windows_amd64.zip
    - $RELEASES_PATH/snapshot/circlecrossgame_darwin_386.zip
    - $RELEASES_PATH/snapshot/circlecrossgame_darwin_amd64.zip
    - $RELEASES_PATH/snapshot/circlecrossgame_linux_386.tar.gz
    - $RELEASES_PATH/snapshot/circlecrossgame_linux_amd64.tar.gz
    - $RELEASES_PATH/snapshot/circlecrossgame_linux_arm.tar.gz
  on:
    repo: kusabashira/circlecrossgame
    tags: true
